language: scala
matrix:
  include:
    - scala: 2.12.7
      jdk: oraclejdk8

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.ivy2/cache

script:
  - sbt test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

notifications:
  email:
    - flatmap-squad@spotify.com
